# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  dev_db:
    image: postgres:13
    container_name: dev_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: development
      POSTGRES_DB: dev
    ports:
      - 5433:5432

  test_db:
    image: postgres:13
    restart: always
    container_name: test_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tests

  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app

    depends_on:
      - dev_db

    environment:
      DATABASE_URL: postgres://development:password@dev_db:5432/dev
