# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  test_db:
    image: postgres:13
    restart: always
    container_name: test_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tests
