version: 2.1
orbs:
  # orbs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    steps:
      - checkout
      # build the project
      - node/install:
          node-version: "16.13.0"
      - run:
          name: build the project
          command: |
            echo "NODE --version" 
            echo $(node --version)
            npm run build

  # deploy step will run only after manual approval
  deploy:
    steps:
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy the backend
          command: |
            echo "deploy Backend"
            chmod +x bin/deploy.sh && bin/deploy.sh

workflows:
  coffe-shop:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
